import { Mutable, mongoose } from '@savitri/backend'
import { Beverage } from './beverage.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export interface BeverageDocument extends mongoose.Document {
  name: string,
  alcoholic: string,
  cost: number,
  price: number
}

export class BeverageController extends Mutable<BeverageDocument> {
  constructor() {
    super(Beverage, Description)
  }
}