import { Mutable } from '@savitri/backend'
import { Beverage, BeverageDocument } from './beverage.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export class BeverageController extends Mutable<BeverageDocument> {
  constructor() {
    super(Beverage, Description)
  }
}