import { Mutable, mongoose } from '@savitri/backend'
import { Customer } from './customer.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export interface CustomerDocument extends mongoose.Document {
  name: string,
  address: string,
  phone: number,
  allergies: string
}

export class CustomerController extends Mutable<CustomerDocument> {
  constructor() {
    super(Customer, Description)
  }
}