import { Mutable } from '@savitri/backend'
import { CustomerDocument } from "../interfaces/customer"
import { Customer } from './customer.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export class CustomerController extends Mutable<CustomerDocument> {
  constructor() {
    super(Customer, Description)
  }
}