import { Mutable } from '@savitri/backend'
import { PizzaDocument, Pizza } from './pizza.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    Pizzas disponíveis no cardápio do estabelecimento. O usuário cadastra o nome da pizza e os ingredientes e o preço é automaticamente calculado.
*/

export class PizzaController extends Mutable<PizzaDocument> {
  constructor() {
    super(Pizza, Description)
  }
}
