import { Mutable, mongoose } from '@savitri/backend'
import { Pizza } from './pizza.model'
import { IngredientDocument } from '../ingredient/ingredient.controller'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    Pizzas disponíveis no cardápio do estabelecimento. O usuário cadastra o nome da pizza e os ingredientes e o preço é automaticamente calculado.
*/

export interface PizzaDocument extends mongoose.Document {
  name: string
  ingredients: IngredientDocument[]
  price_small: number
}

export class PizzaController extends Mutable<PizzaDocument> {
  constructor() {
    super(Pizza, Description)
  }
}
