import { Mutable, mongoose } from '@savitri/backend'
import { Ingredient } from './ingredient.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export interface IngredientDocument extends mongoose.Document {
  name: string,
  price: number
}

export class IngredientController extends Mutable<IngredientDocument> {
  constructor() {
    super(Ingredient, Description)
  }
}
