import { Mutable } from '@savitri/backend'
import { IngredientDocument } from '../interfaces/ingredient'
import { Ingredient } from './ingredient.model'
import { default as Description } from './index.json'

/**
    @remarks Generated by savitrigen
    @copyright Protolab Systems
    undocumented
*/

export class IngredientController extends Mutable<IngredientDocument> {
  constructor() {
    super(Ingredient, Description)
  }
}
